### PR TITLE
Proper future use

### PR DESCRIPTION
**Pull request by daniele-athome**
Due to the nature of widget rebuilding in Flutter, future.then might be invoked more than once, causing undesired effects.
The solution (as I see it) is to convert the widget to a stateful widget and use the widget state to store the future (and applying the callbacks once in initState).

This PR includes modifications from #2 (which I will close).

### CODE REVIEW

**Comment by daniele-athome** [comment]
I also took the liberty of upgrading the dependencies in the lock file and applying some lint fixes (mainly `const`s).

**Comment by daniele-athome** [comment]
@donguseo any chance you could take a look at this? Thanks.

**Comment by donguseo** [comment]
> @donguseo any chance you could take a look at this? Thanks.

@daniele-athome 
I am really sorry that I have made you to wait so long. 
Because of my personal problems, I didn't have time to looking at this repo.

In this weekend or next week, I might have time to check your PR and publish next version. 
If there is any update, I will let you know. 

Thank you very much for making this PR.

**Comment by daniele-athome** [comment]
No problem man, whenever you have time. I'm using my own fork in the meantime.

**Review by donguseo — APPROVED** [review]

**Comment by donguseo** [comment]
@daniele-athome just updated 0.2.1 version
Thank you!

**Pull request merged**
